---
- name: Update apt and install curl gnupg apt-transport-https
  package:
    update_cache: true
    name:
      - curl
      - gnupg
      - apt-transport-https
      - debian-archive-keyring
    state: present

- name: Install nftables when using firewall bouncer
  package:
    name:
      - nftables
    state: present
  when: crowdsec_install_firewall_bouncer|bool

- name: Start nftables services
  service:
    name: nftables
    state: started
    enabled: true
  when:
    - default_os_firewall == 'nftables'
    - crowdsec_install_firewall_bouncer|bool

- name: Crowdsec Add GPG apt Key
  apt_key:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    state: present

- name: Crowdsec Add Repository
  apt_repository:
    repo: "deb https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution | lower  }} {{ansible_distribution_release | lower}} main"
    state: present
