---
# Debian based
# Upstream recommened way.
# See https://discourse.crowdsec.net/t/no-firewall-bouncer-in-repo-for-ubuntu-24-04/2478/3
- name: Install firewall bouncer for Debian
  when:
    - cs_firewall_bouncer
    - ansible_os_family | lower == "debian"
  block:
    - name: Ensure required packages are present
      ansible.builtin.apt:
        name:
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes
      # Avoid run apt ansible module on very old debian. It is broken.
      when: >
        ansible_distribution != "Debian" or
        (ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 11)

    - name: Add CrowdSec GPG key
      ansible.builtin.apt_key:
        url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
        state: present

    - name: Add CrowdSec apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb https://packagecloud.io/crowdsec/crowdsec/ubuntu
          {{ ansible_distribution_release | lower }} main
        filename: crowdsec_crowdsec
        state: present
      # Avoid run apt ansible module on very old debian. It is broken.
      when: >
        ansible_distribution != "Debian" or
        (ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 11)

    - name: Install nftables when using firewall bouncer
      package:
        name: crowdsec-firewall-bouncer-nftables
        update_cache: true
        state: present
      # Avoid run apt ansible module on very old debian. It is broken.
      when: >
        ansible_distribution != "Debian" or
        (ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 11)

    - name: Install repo for old Debian with fresh ansible version
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/crowdsec_crowdsec.list
        content: "deb https://packagecloud.io/crowdsec/crowdsec/debian {{ ansible_distribution_release | lower }} main\n"
        force: yes
      when: ansible_distribution == "Debian" and ansible_distribution_major_version | int < 11


# RedHAT
- name: Crowdsec-firewall-bouncer-nftables
  package:
    update_cache: yes
    name: crowdsec-firewall-bouncer-nftables
    state: present
  when:
    - cs_firewall_bouncer
    - ansible_os_family | lower == "redhat"
    - ansible_distribution_major_version > '7'

- name: Crowdsec-firewall-bouncer-iptables
  package:
    update_cache: true
    name: crowdsec-firewall-bouncer-iptables
    state: present
  when:
    - ansible_os_family | lower == "redhat"
    - ansible_distribution_major_version == '7'
    - cs_firewall_bouncer


# Config
- name: Configure crowdsec-firewall-bouncer when using lapi server (1/3)
  template:
    src: "{{ lookup('first_found', params) }}"
    dest: "/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml"
    owner: root
    group: root
    mode: "0644"
  vars:
    params:
      files:
        - bouncer-firewall/crowdsec-firewall-bouncer.yaml.j2
      paths:
        - "{{ cs_template_dir }}"
        - templates
  notify:
    - Restart crowdsec-firewall-bouncer
  when:
    - cs_lapi_ip is defined
    - cs_firewall_bouncer


# Service
- name: Crowdsec-firewall-bouncer enable and start service
  service:
    name: crowdsec-firewall-bouncer
    state: started
    enabled: true
  when:
    - cs_firewall_bouncer

- name: Crowdsec-firewall-bouncer disable and stop service
  service:
    name: crowdsec-firewall-bouncer
    state: stopped
    enabled: false
  when:
    - not cs_firewall_bouncer
