---
- name: Crowdsec - set install config dir
  set_fact:
    cs_config_dir: >-
      {{ '{{ cs_docker_install_dir }}/volumes/etc_crowdsec/' if cs_install_type == 'docker' else '/etc/crowdsec/' }}
    cs_exec_insert: >-
      {{ 'docker exec crowdsec ' if cs_install_type == 'docker' else '' }}

- name: Gen agent key
  set_fact:
    cs_agent_key: >-
      {{ (inventory_hostname + cs_agent_secret) | hash('sha256') | truncate(32, end='') }}
  when:
    - cs_lapi_agent

- name: Gen bouncer key
  set_fact:
    cs_bouncer_key: >-
      {{ (inventory_hostname + cs_bouncer_secret) | hash('sha256') | truncate(32, end='') }}
  when:
    - cs_firewall_bouncer

- name: Crowdsec - direct installation
  include_tasks: direct/main.yml
  when: cs_install_type == 'direct'

- name: Crowdsec - docker installation
  include_tasks: docker/main.yml
  when: cs_install_type == 'docker'

- name: Crowdsec - make configs
  include_tasks: make-configs.yml

- name: Crowdsec - firewall bouncer installation (direct)
  include_tasks: firewall-bouncer.yml
  when:
    - cs_firewall_bouncer

- name: Add machines and bouncers to lapi server
  include_tasks: add-machines-and-bouncers.yml
  when:
    - cs_lapi_server
