---
- name: Install nftables
  dnf:
    name: nftables
    state: present
  when: cs_firewall_bouncer|bool

- name: Start nftables services
  service:
    name: nftables
    state: started
    enabled: yes
  when: cs_firewall_bouncer|bool

- name: Copy crowdsec repo file into place.
  template:
    src: templates/redhat/crowdsec_crowdsec.j2
    dest: /etc/yum.repos.d/crowdsec_crowdsec.repo
    owner: root
    group: root
    mode: "0644"
