---
- name: Crowdsec - docker - mkdir volumes dir
  file:
    path: "{{ cs_docker_install_dir }}/volumes/{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - etc_crowdsec/hub
    - etc_crowdsec/notifications
    - etc_crowdsec/patterns
    - etc_crowdsec/parsers/s02-enrich
    - var_lib_crowdsec_data
  when: cs_lapi_server or cs_lapi_agent

- name: Crowdsec - docker - docker-compose.yml
  template:
    src: docker/docker-compose.yml.j2
    dest: "{{ cs_docker_install_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart crowdsec-docker
  when: cs_lapi_server or cs_lapi_agent

- name: Crowdsec - docker - crowdsec-docker systemd config
  template:
    src: docker/crowdsec-docker.service.j2
    dest: "/etc/systemd/system/crowdsec-docker.service"
    mode: '0644'
  notify: 'Reload systemd'
  when: cs_lapi_server or cs_lapi_agent

- name: Crowdsec-docker enable and start service
  service:
    name: crowdsec-docker
    state: started
    enabled: true
  when:
    - cs_enabled
    - cs_lapi_server or cs_lapi_agent

- name: Crowdsec disable and stop service
  service:
    name: crowdsec-docker
    state: stopped
    enabled: false
  when:
    - not cs_enabled

- name: Uninstall crowdsec on host (direct)
  ansible.builtin.package:
    name: crowdsec
    state: absent
  when:
    - cs_install_type != 'direct'
